#config_version=6


##! mode: ball_save
mode:
  start_events: ball_started
  stop_events: ball_ending


ball_saves:
  ball_save:
    active_time: 8s
    hurry_up_time: 5s
    timer_start_events: balldevice_bd_trough_ball_eject_success
    balls_to_save: 1
    early_ball_save_events: s_left_outlane_active, s_right_outlane_active

slide_player:
  mode_ball_save_started: ball_save