#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_hero_select_mode
  s_start_active: sw_add_player

sound_player:
  mode_base_started:
    WoL1:
      bus: music

slide_player:
  mode_base_started: base

variable_player:
  s_right_inlane_active:
    score: 100
  s_left_flipper_active:
    score: 1000
