#config_version=6

hardware:
  platform: smart_virtual
  #platform: virtual_pinball #this is for the VPX bridge



virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

displays:
  window:
    height: 1080
    width: 1920

config:
  - config_switches.yaml
  - config_ball_devices.yaml
  - config_coils.yaml

game:
  add_player_switch_tag: add_player

modes:
  - attract
  - base
  - hero_select
  - high_score

slide_player:
  mode_attract_started: attract


player_vars:
  minerals:
    initial_value: 200
  gas:
    initial_value: 150
  supply:
    initial_value: 10
