#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

switches:
  s_left_flipper:
    number:  #this can be blank if you dont have physical hardware
    tags: left_flipper
  s_right_flipper:
    number:  #blank with no hw, but a number is assigned baseed on your
    #pinball controller and what switch input its in
    tags: right_flipper
  s_trough1:
    number: 1
  s_trough2:
    number: 2
  s_trough3:
    number: 3
  s_trough4:
    number: 4
  s_trough5: #may not exist with real hardware
    number: 5
  s_trough6:
    number: 6
  s_trough_jam:
    number: 7
  s_plunger:
    number: 10
  s_start:
    number: 11
    tags: start
  s_right_inlane:
    number: 12
      tags: playfield_active

    
virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

keyboard:
  z:
    switch: s_left_flipper
  y:
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  p:
    switch: s_plunger
    toggle: true

coils:
  c_flipper_left_main:
    number:   # again, these numbers will probably be different for you
    default_pulse_ms: 10 #may need to adjust this when you get real hardware, default was 10, then 20 for tut
  c_flipper_left_hold:
    number:   # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    number: 
    default_pulse_ms: 10 #may change later
  c_flipper_right_hold:
    number: 
    allow_enable: true
  c_trough_eject:
    number: 3

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger 
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true


playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger  # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
  

displays:
  window:
    width: 800
    height: 600

config:
  -config_switches.yaml

modes:
  - attract
  - base
